export const jobData = [
  {
    name: "Tyro Payments",
    role: "Software Engineer",
    time: "Oct 2022 - Present",
    url: "https://www.tyro.com",
    description: [
      "Development using React, TypeScript, Redux and Node.js, contributing through the whole delivery life cycle, from inception to production, through to planning, development and testing",
      "Building services and APIs",
      "Collaborative working together with other engineers, product managers and UX designers"
    ],
  },
  {
    name: "Jaxsta",
    role: "Software Engineer",
    time: "Nov 2021 - Oct 2022",
    url: "https://jaxsta.com",
    description: [
      "Developing new features and maintaining the Jaxsta web application using React, Next.js, TypeScript, Ember.js and JavaScript as part of a tightly-knit, fast moving agile development team",
      "Contributing to the front end product and consumer facing architecture for the Jaxsta website of over 65 million pages incorporating internally developed API's and CMS based content",
      "Assist with defining and scoping features and development tasks",
      "Perform code reviews and provide feedback to other team members that is constructive, designed to support and improve capability",
      "Produce and maintain documentation in Confluence using defined standards",
      "Contribute to automated browser and device testing and bug fixing",
      "Working on Front-end Distributed Systems Architectures and micro-services",
      "Work with AWS mainly on S3, CloudFront, WAF and API Gateway",
      "Developed a private Chrome extension to automate some tasks",
    ],
  },
  {
    name: "Cider House ICT",
    role: "Full Stack Developer & Network Support",
    time: "Apr 2021 - Nov 2021",
    url: "https://ciderhouse.com.au",
    description: [
      " Developing and maintaining web applications using Node.js, PHP, SQL, JavaScript, HTML, Bootstrap, jQuery and REST APIs",
      "Providing technical and network support to clients for in-house developed software applications via phone, chat channels and remote connections",
      "Assist in installation of software and setting up of network and servers for clients",
      "Development of task automation scripts using PowerShell",
      "Configuration and assembling of computer hardware and software",
      "Writing new and update existing documentation for software applications",
      "Developing Excel VBA Macros for data analysis",
    ],
  },
  {
    name: "BeerCo.com.au",
    role: "Software Engineer",
    time: "Nov 2020 - Dec 2021",
    url: "https://beerco.com.au",
    description: [
      "Shopify development and website maintenance",
      "Development of custom web applications using Liquid, HTML, CSS, JavaScript, AJAX, PHP and jQuery",
      "Developed a custom Chrome browser extension for filtering postcodes based on shipping surcharges",
      "Developed a Shopify Product Bundler app using React.js, Node.js, MongoDB, Webhooks and REST APIs deployed on Heroku",
      "Developing a multi-seller marketplace app using Shopify REST APIs",
      "Increasing the web traffic and organic search engine results of the organization through Search Engine Optimization (SEO)",
      "Managing the social media platforms of the organisation",
    ],
  },
  {
    name: "Single Use Ain't Sexy",
    role: "Shopify Developer",
    time: "Sep 2021 - Present",
    url: "https://singleuseaintsexy.com",
    description: [
      "Developing, maintaining and making custom changes to the Shopify website",
    ],
  },
  {
    name: "Cognizant",
    role: "Programmer Analyst",
    time: "Nov 2017 - Jul 2019",
    url: "https://cognizant.com",
    description: [
      "Provided IT services like Analysis and Design, Software development and Active Directory management in the domain of Cyber Security",
      "Developing web apps using HTML, CSS, JavaScript and JSP, performing back-end XML to JSON formatting",
      "Documenting and maintaining user documentation, system plans and operational procedures",
      "Diagnosing, debugging and fixing security issues in software applications",
      "Played different roles in projects to meet the client requirements and worked on different modules and applications projects",
      "Driving key operational services such as Problem Management and Change Management for improving the application stability and functionality",
      "Worked on certificate updation in DataPower services, IP Whitelisting and adding new junctions in WebSEAL instances",
      "Performed Log monitoring in Splunk, DataPower service and WebSEAL instance monitoring and incident ticket resolution in ServiceNow",
      "Maintaining the weekly and monthly ISAM and DataPower status report generation and application monitoring",
      "Experienced in security tools like IBM Security Access Manager (ISAM), Tivoli Access Manager (TAM), IBM DataPower and Oracle Enterprise Single Sign-On",
    ],
  },
];
