export const jobData = [
  {
    name: "Jaxsta Music",
    role: "Software Engineer",
    url: "www.jaxsta.com",
    description: [
      "Developing new features and maintaining the Jaxsta web application using React, Next.js, TypeScript, Ember.js and JavaScript as part of a tightly-knit, fast moving agile development team",
      "Contributing to the front end product and consumer facing architecture for the Jaxsta website of over 65 million pages incorporating internally developed API's and CMS based content",
      "Assist with defining and scoping features and development tasks",
      "Perform code reviews and provide feedback to other team members that is constructive, designed to support and improve capability",
      "Produce and maintain documentation in Confluence using defined standards",
      "Contribute to automated browser and device testing and bug fixing",
      "Working on Front-end Distributed Systems Architectures and micro-services",
      "Work with AWS mainly on S3, CloudFront, WAF and API Gateway",
    ],
  },
  {
    name: "Cider House ICT",
    role: "Full Stack Developer & Network Support",
    url: "www.ciderhouse.com.au",
    description: [
      " Developing and maintaining web applications using Node.js, PHP, SQL, JavaScript, HTML, Bootstrap, jQuery and REST APIs",
      "Providing technical and network support to clients for in-house developed software applications via phone, chat channels and remote connections",
      "Assist in installation of software and setting up of network and servers for clients",
      "Development of task automation scripts using PowerShell",
      "Configuration and assembling of computer hardware and software",
      "Writing new and update existing documentation for software applications",
      "Developing Excel VBA Macros for data analysis",
    ],
  },
  {
    name: "BeerCo.com.au",
    role: "Software Engineer",
    url: "www.beerco.com.au",
    description: [
      "Shopify development and website maintenance",
      "Development of custom web applications using Liquid, HTML, CSS, JavaScript, AJAX, PHP and jQuery",
      "Developed a Shopify Product Bundler app using React.js, Node.js, MongoDB, Webhooks and REST APIs deployed on Heroku",
      "Developing a multi-seller marketplace app using Shopify REST APIs",
      "Increasing the web traffic and organic search engine results of the organization through Search Engine Optimization (SEO)",
      "Managing the social media platforms of the organisation",
    ],
  },
  {
    name: "Single Use Ain't Sexy",
    role: "Shopify Developer",
    url: "www.singleuseaintsexy.com",
    description: [
      "Developing, maintaining and making custom changes to the Shopify website",
    ],
  },
  {
    name: "Cognizant",
    role: "Programmer Analyst",
    url: "www.cognizant.com",
    description: [
      "Provided IT services like Analysis and Design, Software development and Active Directory management in the area of Cyber Security application support",
      "Developed websites using HTML, CSS and JavaScript and performed back-end JSON formatting",
      "Experienced in IBM security tools like IBM Security Access Manager (ISAM), Tivoli Access Manager (TAM) and IBM DataPower",
      "Worked on certificate updation in DataPower services, IP Whitelisting and adding new junctions in WebSEAL instances",
      "Played different roles in projects to meet the client requirements and worked on different modules and applications projects as a Support Analyst",
      "Performed Log monitoring in Splunk, DataPower service and WebSEAL instance monitoring and Incident ticket resolution in ServiceNow",
      "Provided Level 1 and Level 2 support on application issues and provided customer support",
      "Maintaining the weekly and monthly ISAM and DataPower status report generation and application monitoring",
      "Driving key operational services such as Problem Management and Change Management for improving the application stability and functionality",
      "Also worked on Oracle Enterprise Single Sign-On",
    ],
  },
];
